In [20]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

In [3]:
df.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01


Q2. Records count

In [6]:
df.shape

(2160, 12)

there is 2160 records

Q3. Laptop brands

In [10]:
df["Brand"].nunique()

27

In [11]:
df.isnull().any().sum()

np.int64(3)

In [12]:
df[df["Brand"] == "Dell"]["Final Price"].max()

np.float64(3936.0)

In [13]:
df["Screen"].median()

np.float64(15.6)

In [15]:
mode_value = df["Screen"].mode()[0]
print(mode_value)

15.6


In [16]:
df["Screen"] = df["Screen"].fillna(mode_value)

In [17]:
df["Screen"].median()

np.float64(15.6)

In [19]:
# Step 1: Filter Innjoo laptops
df_innjoo = df[df["Brand"] == "Innjoo"]

# Step 2: Select columns
X = df_innjoo[["RAM", "Storage", "Screen"]].values
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [22]:
# Step 3: Compute XTX
XTX = X.T @ X

# Step 4: Inverse of XTX
XTX_inv = np.linalg.inv(XTX)

# Step 5: Create y
y = np.array([1100, 1300, 800, 900, 1000, 1100])

# Step 6: Compute w
w = XTX_inv @ X.T @ y

# Step 7: Sum of elements
print(w.sum())

91.2998806299555
